name: Feature Request
description: A new feature that implements a requirement from Repo A
title: "[Feature] <short description>"
labels: [feature]

body:
  - type: input
    id: requirement_link
    attributes:
      label: Requirement Link
      description: Link to the related requirement issue in Repo A (e.g., `peterbrightwell/reqs#99999`)
      placeholder: "peterbrightwell/reqs#99999"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the feature and how it fulfills the requirement.
      placeholder: "Describe the implementation plan, scope, and any dependencies."
    validations:
      required: true
